//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrabCarMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class deshConnection : DbContext
    {
        public deshConnection()
            : base("name=deshConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ditcltest> ditcltests { get; set; }
        public virtual DbSet<PayPageObjectRole> PayPageObjectRoles { get; set; }
        public virtual DbSet<PayPageObject> PayPageObjects { get; set; }
        public virtual DbSet<PayRole> PayRoles { get; set; }
        public virtual DbSet<AppUser> AppUsers { get; set; }
        public virtual DbSet<booking_driver> booking_driver { get; set; }
        public virtual DbSet<driver_rating> driver_rating { get; set; }
        public virtual DbSet<FairChart> FairCharts { get; set; }
        public virtual DbSet<FAQ> FAQs { get; set; }
        public virtual DbSet<gcm_users> gcm_users { get; set; }
        public virtual DbSet<history> histories { get; set; }
        public virtual DbSet<HomePage> HomePages { get; set; }
        public virtual DbSet<HowItWork> HowItWorks { get; set; }
        public virtual DbSet<ServiceTimeSlot> ServiceTimeSlots { get; set; }
        public virtual DbSet<ServiceType> ServiceTypes { get; set; }
        public virtual DbSet<tblInstruction> tblInstructions { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<user_driver> user_driver { get; set; }
    }
}
