//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrabCarMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HowItWork
    {
        public int Id { get; set; }
        public Nullable<int> Step { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
