//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrabCarMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayPageObject
    {
        public int PageObjectId { get; set; }
        public string PageTypeName { get; set; }
        public string PageName { get; set; }
        public string PagePath { get; set; }
        public string PageMethodeName { get; set; }
    }
}
